//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location_voitures_ADO_console.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.LOUE = new HashSet<LOUE>();
        }
    
        public int ID_CLIENT { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public System.DateTime DATE_DE_NAISSANCE { get; set; }
        public string ADRESSE { get; set; }
        public int CODE_POSTAL { get; set; }
        public string VILLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOUE> LOUE { get; set; }
    }
}
