//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location_voitures_ADO_console.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOUE
    {
        public int ID_CLIENT { get; set; }
        public int VEHICULE_ID { get; set; }
        public int NB_KM { get; set; }
        public System.DateTime DATE_DEBUT { get; set; }
        public System.DateTime DATE_FIN { get; set; }
        public int ID_LOCATION { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
    }
}
