// <auto-generated />
namespace Location_voitures_ADO_console.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AJOUT_PAYS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AJOUT_PAYS));
        
        string IMigrationMetadata.Id
        {
            get { return "201809131327054_AJOUT_PAYS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
